ABPosSolutions.TechnicalTest.Web/Controllers/BuildingController.cs
using ABPosSolutions.TechnicalTest.Application.Features.Buildings.Commands.CreateBuilding;
using ABPosSolutions.TechnicalTest.Application.Features.Buildings.Commands.UpdateBuilding;
using ABPosSolutions.TechnicalTest.Application.Features.Buildings.Queries.GetAllBuildings;
using ABPosSolutions.TechnicalTest.Application.Features.Buildings.Queries.GetBuildingById;
using ABPosSolutions.TechnicalTest.Domain;
using ABPosSolutions.TechnicalTest.Web.Models;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace ABPosSolutions.TechnicalTest.Web.Controllers
{
    public class BuildingController : Controller
    {
        private readonly IMediator mediator;
        private readonly IMapper mapper;

        public BuildingController(IMediator mediator, IMapper mapper)
        {
            this.mediator = mediator;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            GetAllBuildingsQuery query = new GetAllBuildingsQuery();
            List<Building> buildings = await mediator.Send(query);
            return View(buildings);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            CreateBuildingDto dto;
            if (string.IsNullOrEmpty(id))
            {
                dto = new CreateBuildingDto();
            }
            else
            {
                Building building = await GetBuildingAsync(id);
                dto = new CreateBuildingDto
                {
                    Address = building.Address,
                    BuildingName = building.BuildingName,
                };
            }
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Detail(CreateBuildingDto dto)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(dto.Id))
                {
                    CreateBuildingCommand command = mapper.Map<CreateBuildingCommand>(dto);
                    Building building = await mediator.Send(command);
                    return RedirectToAction("Detail", new { id = building.Id });
                }
                else
                {
                    UpdateBuildingCommand command = mapper.Map<UpdateBuildingCommand>(dto);
                    Building building = await mediator.Send(command);
                    return RedirectToAction("Detail", new { id = building.Id });
                }
            }
            else
            {
                return View(dto);
            }
            
        }

        private async Task<Building> GetBuildingAsync(string id)
        {
            try
            {
                GetBuildingByIdQuery query = new GetBuildingByIdQuery() { Id = id};
                Building building = await mediator.Send(query);
                return building;
            }
            catch (Exception e)
            {

                throw;
            }
        }
    }
}

ABPosSolutions.TechnicalTest.Web/Views/Building/Detail.cshtml
@model ABPosSolutions.TechnicalTest.Web.Models.CreateBuildingDto
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Detail" asp-controller="Building">
    <div asp-validation-summary=ModelOnly></div>
    @if (Model.Id != null)
    {
        <input type="hidden" asp-for="Id"/>
    }
  <div class="form-group">
    <label asp-for="BuildingName"></label>
    <input asp-for="BuildingName" class="form-control" >
    <span asp-validation-for="BuildingName" class="text-danger small"></span>
  </div>
  <div class="form-group">
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control" >
    <span asp-validation-for="Address" class="text-danger small"></span>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ABPosSolutions.TechnicalTest.Web/Views/Building/Index.cshtml
@model List<ABPosSolutions.TechnicalTest.Domain.Building>
@{
    ViewData["Title"] = "Buildings";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int index = 1;
}

<a asp-action="Detail" asp-controller="Building" class="btn-primary btn">Create Building</a>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Names</th>
      <th scope="col">Address</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <th scope="row">@(index++)</th>
            <td>@item.BuildingName</td>
            <td>@item.Address</td>
            <td>
                <a class="btn-success btn" asp-action="Detail" asp-controller="Building" asp-route-id="@item.Id">Detail</a>
            </td>
        </tr>
    }
  </tbody>
</table>